// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzh1jMwv6V67Z8xwRyHAiRax75j42BQWQ',
    appId: '1:26570862721:android:28ce39365510e9864d9d80',
    messagingSenderId: '26570862721',
    projectId: 'phipos-d3f4e',
    storageBucket: 'phipos-d3f4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjZTkji6CiqtMWRYItDtmovTpY4xU6ak',
    appId: '1:26570862721:ios:a19653384c3244ca4d9d80',
    messagingSenderId: '26570862721',
    projectId: 'phipos-d3f4e',
    storageBucket: 'phipos-d3f4e.appspot.com',
    iosClientId: '26570862721-022rb7h4vab09bpjskb7tgrbrqnsfchc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pihorizonn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxc_L1mTuGqMX9l3byPh6Bkz53wDmvE0',
    appId: '1:26570862721:web:6514d6ae622177084d9d80',
    messagingSenderId: '26570862721',
    projectId: 'phipos-d3f4e',
    authDomain: 'phipos-d3f4e.firebaseapp.com',
    storageBucket: 'phipos-d3f4e.appspot.com',
    measurementId: 'G-MX3LLQFF1Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjZTkji6CiqtMWRYItDtmovTpY4xU6ak',
    appId: '1:26570862721:ios:a19653384c3244ca4d9d80',
    messagingSenderId: '26570862721',
    projectId: 'phipos-d3f4e',
    storageBucket: 'phipos-d3f4e.appspot.com',
    iosClientId: '26570862721-022rb7h4vab09bpjskb7tgrbrqnsfchc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pihorizonn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXxc_L1mTuGqMX9l3byPh6Bkz53wDmvE0',
    appId: '1:26570862721:web:1be39cd6f28097944d9d80',
    messagingSenderId: '26570862721',
    projectId: 'phipos-d3f4e',
    authDomain: 'phipos-d3f4e.firebaseapp.com',
    storageBucket: 'phipos-d3f4e.appspot.com',
    measurementId: 'G-714JLVG5GZ',
  );

}